name: bookingstore
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.0
  get_storage: ^2.1.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.7.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

